---
- name: Prepare enviroment for build machine
  hosts: localhost
  tasks:
  - name: Add PPA
    become: yes
    apt_repository: repo='ppa:webupd8team/java'

  - name: Accept Java 8 License
    sudo: yes
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

  - name: Install git
    become: yes
    apt: name={{item}} update_cache=yes
    with_items:
      - git
      - oracle-java8-installer
      - oracle-java8-set-default
  - name: Put source file
    template: src=/init-onos dest=~/init-onos

  - name: Pull ONOS
    git: repo=https://github.com/opennetworkinglab/onos.git dest=~/onos

  - name: Download Apache Karaf 3.0.5
    command: 'wget ftp://140.113.169.97/apache-karaf-3.0.5.tar.gz -P ~/Downloads/'

  - name: Download Apache Maven 3.3.9
    command: 'wget ftp://140.113.169.97/apache-maven-3.3.9-bin.tar.gz -P ~/Downloads/'

  - name: Create Application Director
    file: path=~/Applications state=directory mode=0775

  - name: Unarchive Apache Karaf 3.0.5
    unarchive: src=~/Downloads/apache-karaf-3.0.5.tar.gz dest=~/Applications

  - name: Unarchive Apache Maven 3.3.9
    unarchive: src=~/Downloads/apache-maven-3.3.9-bin.tar.gz dest=~/Applications

  - name: Compile ONOS
    shell: source ~/init-onos && cd ~/onos && mvn clean install && op
    args:
      executable: /bin/bash
